// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdcnKIav05yaeWjnJqoBOX4ZeNQRHJIao',
    appId: '1:780762296475:web:a18b8661bac23ea9a6963e',
    messagingSenderId: '780762296475',
    projectId: 'tikipop-d76b3',
    authDomain: 'tikipop-d76b3.firebaseapp.com',
    storageBucket: 'tikipop-d76b3.appspot.com',
    measurementId: 'G-Z3FHLD8Y4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYg2MYqYM1UDPJ3Q9bE0wLPTgufqBXxq0',
    appId: '1:780762296475:android:4873db528364e12da6963e',
    messagingSenderId: '780762296475',
    projectId: 'tikipop-d76b3',
    storageBucket: 'tikipop-d76b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrruVW8eHOql9gyi6HThnBtV3EgrYWVJ4',
    appId: '1:780762296475:ios:ca2f04e6eea7d03da6963e',
    messagingSenderId: '780762296475',
    projectId: 'tikipop-d76b3',
    storageBucket: 'tikipop-d76b3.appspot.com',
    iosClientId: '780762296475-1v3f519kp968kel841n507kabji8ko50.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikipap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrruVW8eHOql9gyi6HThnBtV3EgrYWVJ4',
    appId: '1:780762296475:ios:82e7a61f5dc86bcea6963e',
    messagingSenderId: '780762296475',
    projectId: 'tikipop-d76b3',
    storageBucket: 'tikipop-d76b3.appspot.com',
    iosClientId: '780762296475-65l7ddte8r0untro93qrlsrvdkaad6r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tikipap.RunnerTests',
  );
}
